<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace dmstr\modules\contact\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "core_dmstr_contact_log".
 *
 * @property integer $id
 * @property string $schema
 * @property string $json
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class ContactLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dmstr_contact_log}}';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['json'], 'string'],
            [['schema'], 'string', 'max' => 64]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'schema' => Yii::t('models', 'Schema'),
            'json' => Yii::t('models', 'Json'),
            'created_at' => Yii::t('models', 'Created At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \dmstr\modules\contact\models\query\ContactLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \dmstr\modules\contact\models\query\ContactLogQuery(get_called_class());
    }


}
